demo:
  image: markusz/docker-demo
  environment:
      NODE_ENV: test
  ports:
   - "8088:300"
  links:
   - mongo
mongo:
  image: mongo:3.0.2
  command: mongod --smallfiles
  ports:
     - "27017:27017"